### ISSUE TITLE
Ignore changes from TimestampBehavior

### ISSUE THREAD

**Issue by jonazu** [nhkey/yii2-activerecord-history#1]
Hi

I'm using TimestampBehavior and ActiveRecordHistoryBehavior, Everytime I save a model ActiveRecordHistoryBehavior saves the "updated_at" field, which is unnecessary.

Regards
Jonas

**Comment by nhkey** [comment]
Hi.

I added property "ignoreFields" in new version 1.1.1, where you can add field "updated_at".
Thanks for issue.

Best regards, Mikhail
