### ISSUE TITLE
Error running ./yii migrate/down

### ISSUE THREAD

**Issue by ddanielroche** [nhkey/yii2-activerecord-history#11]
Hi @nhkey 
After running `./yii migrate/down` the following error occurs:
```sh
PHP Fatal error:  Access to undeclared static property: nhkey\arh\managers\DBManager::$tableName in vendor/nhkey/yii2-activerecord-history/migrations/m150122_115959_activerecordhistory_init.php on line 43
```
I think the right thing is: 
```php
public function down()
{
    $this->dropTable(DBManager::$defaultTableName);
}
```
Good afternoon!

**Comment by nhkey** [comment]
Hi.
It's very strange because this static property used in up-function without problems.

I think it should help:

`./yii migrate/down --migrationPath=@vendor/nhkey/yii2-activerecord-history/migrations`

Maybe you removed this extension and run "migrate/down" after removal?

**Comment by ddanielroche** [comment]
Good Morning @nhkey

Reviewing your source code, I see that the problem was solved by @DD174 in the pull request #8. However this change has not been released, it is only in the development version.
The 1.1.2.1 version is prior to this change.

**Comment by nhkey** [comment]
Oh, sorry, it's my mistake.

I create new release 1.1.2.2 with this changes.

Thanks for your issue!

**Comment by ddanielroche** [comment]
It is a pleasure to contribute.
Regards
