### ISSUE TITLE
Additional attribute "user"

### ISSUE THREAD

**Issue by jonazu** [nhkey/yii2-activerecord-history#2]
Hi again

First of all: Thanks for your support! Much appreciated!

I have a feature request: It would be great to have another attribute "user" where one can save the username who did the change.

Regards
Jonas

**Comment by nhkey** [comment]
Hi, Jonas

I added an attribute "saveUserId" in managerOptions than saved current login user.
By default value of attribute is true.

If you want disable this features, you can use this:
            'history' => [
                'class' => \nhkey\arh\ActiveRecordHistoryBehavior::className(),
                'managerOptions' => [
                    'saveUserId' => false
                ]
            ],

P. S. for update you need do migrations, see update in documentation.

**Comment by jonazu** [comment]
When running the migration I get this error:
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: m151013_131405_add_user_field::string()'

**Comment by nhkey** [comment]
Your version Yii2 must be not less 2.0.6.

Extension used new syntax for migration. [See it](https://github.com/yiisoft/yii2/blob/2.0.6/framework/CHANGELOG.md#206-august-05-2015), Enh #3335.

If you want use old version of framework, you may change migration column type to old style, for example
```php
$this->string()->notNull()
```
to
```php
Schema::TYPE_STRING .' NOT NULL'
```

**Comment by jonazu** [comment]
Thanks for the explanation. Just updated to 2.0.6.
