### ISSUE TITLE
Entry with Id since update after Insert new Record

### ISSUE THREAD

**Issue by Squarius** [nhkey/yii2-activerecord-history#4]
If i create a new record in my table "category' and i have your extension as behavior i get  new history records like this for every new category:

42,"2015-10-13 14:04:23",category,id,82,NULL,NULL,0,1

Thank You for your awesome Work!

**Comment by nhkey** [comment]
Hi
Yes, all right.

42,"2015-10-13 14:04:23",category,id,82,NULL,NULL,0,1
42 - your id in history table;
"2015-10-13 14:04:23" - datetime;
category - your AR-model name;
id - your changed field. So you create new record, changed field is id, it's correct.
82 - id of your object;
NULL - old value of your changed field, not null only after update;
NULL - new value of your changed field, not null only after update;
0 - event (0 - Insert, 1 - Update, 2 - Delete, 3 - Update primary key), you can see it in [this file](https://github.com/nhkey/yii2-activerecord-history/blob/master/src/managers/ActiveRecordHistoryInterface.php);
1 - your user_id, who created object.


I am sorry, documentation is not yet full. In the near future I'll do it.

Best regards, Mikhail.

**Comment by Squarius** [comment]
Okay. Any Idea how can i prevent it? i already tried to change the function to: https://gist.github.com/Squarius/444c1eb8ea5d623e0602

**Comment by nhkey** [comment]
Added new property for this scenario.
Now you can use this construction:
```php
    public function behaviors(){
        return [
            'history' => [
                'class' => \nhkey\arh\ActiveRecordHistoryBehavior::className(),
                'eventsList' => [nhkey\arh\managers\BaseManager::AR_UPDATE],
               ...
            ],
        ...
        ];
    }
```

With this code in history log table saved only updates of your AR objects.

**Comment by Squarius** [comment]
Awesome. Thank You!



```
public function behaviors(){
        return [
            'history' => [
                'class' => \nhkey\arh\ActiveRecordHistoryBehavior::className(),
                'eventsList' => [\nhkey\arh\managers\BaseManager::AR_UPDATE],
               ...
            ],
        ...
        ];
    }
```
