### ISSUE TITLE
Checkbox values saved without change

### ISSUE THREAD

**Issue by jonazu** [nhkey/yii2-activerecord-history#6]
Hi again

I'm using some checkboxes and they get saved in the history table without a change in the values. Can you reprocude this behaviour?

Thanks for your help
Jonas

**Comment by nhkey** [comment]
Hi, Jonas.

How you store values of checkbox in your DB?

**Comment by jonazu** [comment]
It's tinyint(1)

**Comment by nhkey** [comment]
It is very strange. I tested different scenarios and options, but could not repeat this behavior. Could you give a piece of code controller, model and view?
